spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:1010/realms/learninRelam
